version: '3.4'
services:
  fluentd:
    build:
      context: .
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - /tmp/:/fluentd/log/
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300